-- ============================================================
-- V002__crear_rol_participante_y_catalogo.sql
-- Proyecto: Sistema de Gestión de Eventos
-- Motor: PostgreSQL
-- Jira: SCRUM-43
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS rol_participante (
    id_rol_participante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(50)  NOT NULL,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_rol_participante_codigo UNIQUE (codigo),
    CONSTRAINT uq_rol_participante_nombre UNIQUE (nombre),
    CONSTRAINT ck_rol_participante_codigo_no_vacio CHECK (BTRIM(codigo) <> ''),
    CONSTRAINT ck_rol_participante_nombre_no_vacio CHECK (BTRIM(nombre) <> '')
);

COMMENT ON TABLE rol_participante IS
'Catálogo parametrizable de roles que una persona puede desempeñar dentro de un evento.';

INSERT INTO rol_participante (codigo, nombre, descripcion)
VALUES
    ('ASISTENTE', 'Asistente',
     'Persona inscripta que participa como asistente en el evento o sus actividades.'),
    ('CONFERENCISTA', 'Conferencista',
     'Persona encargada de exponer, presentar o impartir una actividad del evento.'),
    ('MODERADOR', 'Moderador',
     'Persona responsable de coordinar o moderar una sesión, mesa o actividad.'),
    ('ORGANIZADOR', 'Organizador',
     'Persona que participa en tareas de organización y coordinación del evento.'),
    ('STAFF', 'Staff',
     'Personal de apoyo operativo o logístico durante el desarrollo del evento.')
ON CONFLICT (codigo) DO UPDATE
SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    activo = TRUE,
    actualizado_en = CURRENT_TIMESTAMP;

COMMIT;
