-- ============================================================
-- crear_categoria_actividad_actividad.sql
-- Proyecto: Eventia - Sistema de Gestión de Eventos
-- Motor: PostgreSQL
-- Jira: HU06 / Tarea 6.1
-- Descripción:
--   Crea las tablas CATEGORIA_ACTIVIDAD y ACTIVIDAD.
--
-- Dependencia:
--   EVENTO debe existir previamente.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Tabla: CATEGORIA_ACTIVIDAD
-- Catálogo parametrizable para clasificar actividades del evento.
-- Ejemplos: Conferencia, Taller, Mesa redonda, Charla, Panel.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categoria_actividad (
    id_categoria        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categoria_actividad_nombre
        UNIQUE (nombre),

    CONSTRAINT ck_categoria_actividad_nombre_no_vacio
        CHECK (BTRIM(nombre) <> '')
);

COMMENT ON TABLE categoria_actividad IS
'Catálogo parametrizable de categorías utilizadas para clasificar las actividades de un evento.';

-- ------------------------------------------------------------
-- Tabla: ACTIVIDAD
-- Representa una sesión o actividad programada dentro de un evento.
-- Cada actividad pertenece a un único evento y a una categoría.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS actividad (
    id_actividad        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento           BIGINT       NOT NULL,
    id_categoria        BIGINT       NOT NULL,
    titulo              VARCHAR(150) NOT NULL,
    descripcion         TEXT,
    fecha               DATE         NOT NULL,
    hora_inicio         TIME         NOT NULL,
    hora_fin            TIME         NOT NULL,
    lugar               VARCHAR(200),
    modalidad           VARCHAR(30)  NOT NULL DEFAULT 'PRESENCIAL',
    cupo                INTEGER      NOT NULL,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_actividad_evento
        FOREIGN KEY (id_evento)
        REFERENCES evento (id_evento)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_actividad_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria_actividad (id_categoria)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_actividad_titulo_no_vacio
        CHECK (BTRIM(titulo) <> ''),

    CONSTRAINT ck_actividad_horario
        CHECK (hora_fin > hora_inicio),

    CONSTRAINT ck_actividad_cupo
        CHECK (cupo >= 0),

    CONSTRAINT ck_actividad_modalidad
        CHECK (modalidad IN ('PRESENCIAL', 'VIRTUAL', 'HIBRIDA'))
);

COMMENT ON TABLE actividad IS
'Actividad o sesión programada dentro de la agenda de un evento.';

COMMENT ON COLUMN actividad.modalidad IS
'Modalidad de realización de la actividad: PRESENCIAL, VIRTUAL o HIBRIDA.';

CREATE INDEX IF NOT EXISTS idx_actividad_id_evento
    ON actividad (id_evento);

CREATE INDEX IF NOT EXISTS idx_actividad_id_categoria
    ON actividad (id_categoria);

CREATE INDEX IF NOT EXISTS idx_actividad_evento_fecha_hora
    ON actividad (id_evento, fecha, hora_inicio);

COMMIT;
