-- ============================================================
-- crear_conferencista_actividad_conferencista.sql
-- Proyecto: Eventia - Sistema de Gestión de Eventos
-- Motor: PostgreSQL
-- Jira: HU05 / Tarea 5.1
-- Descripción:
--   Crea las tablas CONFERENCISTA y ACTIVIDAD_CONFERENCISTA.
--
-- Dependencia:
--   ACTIVIDAD debe existir previamente.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Tabla: CONFERENCISTA
-- Catálogo de personas que pueden participar como expositores,
-- moderadores, instructores u otros especialistas en actividades.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conferencista (
    id_conferencista    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres             VARCHAR(100) NOT NULL,
    apellidos           VARCHAR(100) NOT NULL,
    email               VARCHAR(150) NOT NULL,
    institucion         VARCHAR(150),
    biografia           TEXT,
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_conferencista_email
        UNIQUE (email),

    CONSTRAINT ck_conferencista_nombres_no_vacio
        CHECK (BTRIM(nombres) <> ''),

    CONSTRAINT ck_conferencista_apellidos_no_vacio
        CHECK (BTRIM(apellidos) <> ''),

    CONSTRAINT ck_conferencista_email_no_vacio
        CHECK (BTRIM(email) <> '')
);

COMMENT ON TABLE conferencista IS
'Perfil de conferencistas o especialistas que pueden ser asignados a actividades de los eventos.';

-- ------------------------------------------------------------
-- Tabla: ACTIVIDAD_CONFERENCISTA
-- Tabla puente que resuelve la relación muchos-a-muchos entre
-- ACTIVIDAD y CONFERENCISTA.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS actividad_conferencista (
    id_actividad        BIGINT       NOT NULL,
    id_conferencista    BIGINT       NOT NULL,
    rol_en_actividad    VARCHAR(100) NOT NULL DEFAULT 'CONFERENCISTA',
    asignado_en         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_actividad_conferencista
        PRIMARY KEY (id_actividad, id_conferencista),

    CONSTRAINT fk_actividad_conferencista_actividad
        FOREIGN KEY (id_actividad)
        REFERENCES actividad (id_actividad)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_actividad_conferencista_conferencista
        FOREIGN KEY (id_conferencista)
        REFERENCES conferencista (id_conferencista)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ck_actividad_conferencista_rol_no_vacio
        CHECK (BTRIM(rol_en_actividad) <> '')
);

COMMENT ON TABLE actividad_conferencista IS
'Relación muchos-a-muchos entre actividades y conferencistas, indicando el rol que cumple cada persona en la actividad.';

CREATE INDEX IF NOT EXISTS idx_actividad_conferencista_id_conferencista
    ON actividad_conferencista (id_conferencista);

COMMIT;
