-- ============================================================
-- crear_tipo_evento_evento_politica.sql
-- Proyecto: Eventia
-- Motor: PostgreSQL
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS tipo_evento (
    id_tipo_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_tipo_evento_codigo UNIQUE (codigo),
    CONSTRAINT uq_tipo_evento_nombre UNIQUE (nombre),
    CONSTRAINT ck_tipo_evento_codigo_no_vacio CHECK (BTRIM(codigo) <> ''),
    CONSTRAINT ck_tipo_evento_nombre_no_vacio CHECK (BTRIM(nombre) <> '')
);

COMMENT ON TABLE tipo_evento IS
'Catálogo parametrizable de tipos de eventos.';

CREATE TABLE IF NOT EXISTS evento (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_evento BIGINT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    lugar VARCHAR(200) NOT NULL,
    cupo_maximo INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_evento_tipo_evento
        FOREIGN KEY (id_tipo_evento)
        REFERENCES tipo_evento (id_tipo_evento)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_evento_nombre_no_vacio CHECK (BTRIM(nombre) <> ''),
    CONSTRAINT ck_evento_lugar_no_vacio CHECK (BTRIM(lugar) <> ''),
    CONSTRAINT ck_evento_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_evento_cupo_maximo CHECK (cupo_maximo > 0),
    CONSTRAINT ck_evento_estado
        CHECK (estado IN ('BORRADOR', 'PUBLICADO', 'FINALIZADO', 'CANCELADO'))
);

CREATE INDEX IF NOT EXISTS idx_evento_id_tipo_evento
    ON evento (id_tipo_evento);

CREATE INDEX IF NOT EXISTS idx_evento_fecha_inicio
    ON evento (fecha_inicio);

CREATE INDEX IF NOT EXISTS idx_evento_estado
    ON evento (estado);

CREATE TABLE IF NOT EXISTS politica_inscripcion (
    id_politica BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento BIGINT NOT NULL,
    fecha_limite DATE,
    requiere_aprobacion BOOLEAN NOT NULL DEFAULT FALSE,
    permite_lista_espera BOOLEAN NOT NULL DEFAULT FALSE,
    min_asistencia_certificado SMALLINT NOT NULL DEFAULT 0,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_politica_inscripcion_evento UNIQUE (id_evento),

    CONSTRAINT fk_politica_inscripcion_evento
        FOREIGN KEY (id_evento)
        REFERENCES evento (id_evento)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ck_politica_min_asistencia
        CHECK (min_asistencia_certificado BETWEEN 0 AND 100)
);

COMMIT;
