-- ============================================================
-- V001__crear_usuario_rol_sistema_usuario_rol.sql
-- Proyecto: Sistema de Gestión de Eventos
-- Motor: PostgreSQL
-- Jira: SCRUM-10
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS rol_sistema (
    id_rol_sistema      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(50)  NOT NULL,
    nombre              VARCHAR(100) NOT NULL,
    descripcion         VARCHAR(255),
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_rol_sistema_codigo UNIQUE (codigo),
    CONSTRAINT uq_rol_sistema_nombre UNIQUE (nombre),
    CONSTRAINT ck_rol_sistema_codigo_no_vacio CHECK (BTRIM(codigo) <> ''),
    CONSTRAINT ck_rol_sistema_nombre_no_vacio CHECK (BTRIM(nombre) <> '')
);

COMMENT ON TABLE rol_sistema IS
'Catálogo parametrizable de roles de acceso al sistema.';

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres             VARCHAR(100) NOT NULL,
    apellidos           VARCHAR(100) NOT NULL,
    correo              VARCHAR(150) NOT NULL,
    contrasena_hash     VARCHAR(255) NOT NULL,
    activo              BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_acceso       TIMESTAMPTZ,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT ck_usuario_nombres_no_vacio CHECK (BTRIM(nombres) <> ''),
    CONSTRAINT ck_usuario_apellidos_no_vacio CHECK (BTRIM(apellidos) <> ''),
    CONSTRAINT ck_usuario_correo_no_vacio CHECK (BTRIM(correo) <> ''),
    CONSTRAINT ck_usuario_hash_no_vacio CHECK (BTRIM(contrasena_hash) <> '')
);

COMMENT ON TABLE usuario IS
'Usuarios autenticables del Sistema de Gestión de Eventos.';

COMMENT ON COLUMN usuario.contrasena_hash IS
'Hash de contraseña generado por el backend. Nunca almacenar contraseñas en texto plano.';

CREATE TABLE IF NOT EXISTS usuario_rol (
    id_usuario          BIGINT      NOT NULL,
    id_rol_sistema      BIGINT      NOT NULL,
    asignado_en         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario_rol PRIMARY KEY (id_usuario, id_rol_sistema),

    CONSTRAINT fk_usuario_rol_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_usuario_rol_rol_sistema
        FOREIGN KEY (id_rol_sistema)
        REFERENCES rol_sistema (id_rol_sistema)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_usuario_rol_id_rol_sistema
    ON usuario_rol (id_rol_sistema);

COMMIT;
