-- ============================================================
-- crear_participante_inscripcion.sql
-- Proyecto: Eventia
-- Motor: PostgreSQL
--
-- Dependencias:
--   USUARIO
--   ROL_PARTICIPANTE
--   EVENTO
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS participante (
    id_participante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT,
    documento VARCHAR(50) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    institucion VARCHAR(150),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_participante_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_participante_documento_no_vacio CHECK (BTRIM(documento) <> ''),
    CONSTRAINT ck_participante_nombres_no_vacio CHECK (BTRIM(nombres) <> ''),
    CONSTRAINT ck_participante_apellidos_no_vacio CHECK (BTRIM(apellidos) <> ''),
    CONSTRAINT ck_participante_email_no_vacio CHECK (BTRIM(email) <> '')
);

CREATE TABLE IF NOT EXISTS inscripcion (
    id_inscripcion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento BIGINT NOT NULL,
    id_participante BIGINT NOT NULL,
    id_rol_participante BIGINT NOT NULL,
    fecha_inscripcion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) NOT NULL DEFAULT 'CONFIRMADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_inscripcion_evento_participante
        UNIQUE (id_evento, id_participante),

    CONSTRAINT fk_inscripcion_evento
        FOREIGN KEY (id_evento)
        REFERENCES evento (id_evento)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_inscripcion_participante
        FOREIGN KEY (id_participante)
        REFERENCES participante (id_participante)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_inscripcion_rol_participante
        FOREIGN KEY (id_rol_participante)
        REFERENCES rol_participante (id_rol_participante)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_inscripcion_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'CONFIRMADA',
                'LISTA_ESPERA',
                'CANCELADA',
                'RECHAZADA'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_inscripcion_id_participante
    ON inscripcion (id_participante);

CREATE INDEX IF NOT EXISTS idx_inscripcion_id_rol_participante
    ON inscripcion (id_rol_participante);

CREATE INDEX IF NOT EXISTS idx_inscripcion_estado
    ON inscripcion (estado);

COMMIT;
